name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: "clippy --all"
        run: cargo clippy --all --all-features --tests -- -D warnings

      - name: "cargo check"
        run: cargo check --all --all-features

      - name: "cargo test"
        run: |
          cargo test --all
          cargo test --all --all-features
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install poetry venv
        working-directory: python
        run: poetry install
      - name: maturin venv Build
        working-directory: python
        run: poetry run maturin develop
      - name: Run pytest
        working-directory: python
        run: poetry run test
